-- Replace property_addresses entity table with Address table + FK from properties.
-- Migrates existing non-deleted rows and aligns with Property.address_id mapping.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS addresses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID,
    country_code  VARCHAR(2),
    city          VARCHAR(120),
    postcode      VARCHAR(32),
    street        VARCHAR(200),
    street_number VARCHAR(32),
    floor_number  VARCHAR(10),
    lat           DOUBLE PRECISION,
    lng           DOUBLE PRECISION
);

ALTER TABLE addresses ADD COLUMN IF NOT EXISTS uuid UUID;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS country_code VARCHAR(2);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS city VARCHAR(120);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS postcode VARCHAR(32);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS street VARCHAR(200);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS street_number VARCHAR(32);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS floor_number VARCHAR(10);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;

UPDATE addresses
SET uuid = gen_random_uuid()
WHERE uuid IS NULL;

ALTER TABLE addresses ALTER COLUMN uuid SET NOT NULL;
ALTER TABLE addresses ALTER COLUMN country_code SET NOT NULL;
ALTER TABLE addresses ALTER COLUMN city SET NOT NULL;
ALTER TABLE addresses ALTER COLUMN street SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_addresses_uuid ON addresses(uuid);
CREATE INDEX IF NOT EXISTS idx_addresses_city ON addresses(city);
CREATE INDEX IF NOT EXISTS idx_addresses_country ON addresses(country_code);
CREATE INDEX IF NOT EXISTS idx_addresses_postcode ON addresses(postcode);

DO $$ BEGIN
    ALTER TABLE addresses
        ADD CONSTRAINT fk_addresses_country
            FOREIGN KEY (country_code) REFERENCES countries(code);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE properties
    ADD COLUMN IF NOT EXISTS address_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'property_addresses'
    ) THEN
        ALTER TABLE addresses
            ADD COLUMN IF NOT EXISTS legacy_property_id BIGINT UNIQUE;

        INSERT INTO addresses (
            uuid,
            country_code,
            city,
            postcode,
            street,
            street_number,
            floor_number,
            lat,
            lng,
            legacy_property_id
        )
        SELECT
            COALESCE(pa.uuid, gen_random_uuid()),
            pa.country_code,
            pa.city,
            pa.postcode,
            pa.street,
            pa.street_number,
            pa.floor_number,
            pa.lat,
            pa.lng,
            pa.property_id
        FROM property_addresses pa
        WHERE COALESCE(pa.deleted, FALSE) = FALSE
          AND NOT EXISTS (
              SELECT 1
              FROM addresses a
              WHERE a.legacy_property_id = pa.property_id
          );

        UPDATE properties p
        SET address_id = a.id
        FROM addresses a
        WHERE p.id = a.legacy_property_id
          AND p.address_id IS NULL;

        ALTER TABLE addresses
            DROP COLUMN IF EXISTS legacy_property_id;

        DROP TABLE property_addresses;
    END IF;
END $$;

DO $$ BEGIN
    ALTER TABLE properties
        ADD CONSTRAINT fk_properties_address
            FOREIGN KEY (address_id) REFERENCES addresses(id)
            ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_properties_address_id
    ON properties(address_id)
    WHERE address_id IS NOT NULL;
