-- Replace property_photos with shared photos table + properties_photos join table.
-- Preserves IDs so properties.main_photo_id remains valid.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS photos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID,
    url        VARCHAR(600),
    public_id  VARCHAR(600),
    sort_order INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE photos ADD COLUMN IF NOT EXISTS uuid UUID;
ALTER TABLE photos ADD COLUMN IF NOT EXISTS url VARCHAR(600);
ALTER TABLE photos ADD COLUMN IF NOT EXISTS public_id VARCHAR(600);
ALTER TABLE photos ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

UPDATE photos
SET uuid = gen_random_uuid()
WHERE uuid IS NULL;

ALTER TABLE photos ALTER COLUMN uuid SET NOT NULL;
ALTER TABLE photos ALTER COLUMN url SET NOT NULL;
ALTER TABLE photos ALTER COLUMN public_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_photos_uuid ON photos(uuid);

CREATE TABLE IF NOT EXISTS properties_photos (
    property_id BIGINT NOT NULL,
    photo_id    BIGINT NOT NULL,
    PRIMARY KEY (property_id, photo_id),
    CONSTRAINT fk_properties_photos_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_properties_photos_photo
        FOREIGN KEY (photo_id) REFERENCES photos(id)
            ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_properties_photos_property
    ON properties_photos(property_id);

CREATE INDEX IF NOT EXISTS idx_properties_photos_photo
    ON properties_photos(photo_id);

ALTER TABLE properties
    DROP CONSTRAINT IF EXISTS fk_properties_main_photo;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'property_photos'
    ) THEN
        INSERT INTO photos (id, uuid, url, public_id, sort_order)
        SELECT
            pp.id,
            COALESCE(pp.uuid, gen_random_uuid()),
            pp.url,
            pp.public_id,
            COALESCE(pp.sort_order, 0)
        FROM property_photos pp
        ON CONFLICT (id) DO UPDATE
        SET uuid = EXCLUDED.uuid,
            url = EXCLUDED.url,
            public_id = EXCLUDED.public_id,
            sort_order = EXCLUDED.sort_order;

        INSERT INTO properties_photos (property_id, photo_id)
        SELECT pp.property_id, pp.id
        FROM property_photos pp
        ON CONFLICT (property_id, photo_id) DO NOTHING;

        DROP TABLE property_photos;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relkind = 'S'
          AND relname = 'photos_id_seq'
    ) THEN
        PERFORM setval(
            'photos_id_seq',
            COALESCE((SELECT MAX(id) FROM photos), 1),
            TRUE
        );
    END IF;
END $$;

DO $$ BEGIN
    ALTER TABLE properties
        ADD CONSTRAINT fk_properties_main_photo
            FOREIGN KEY (main_photo_id) REFERENCES photos(id)
            ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
