-- ===========================================
-- V1: Core schema for booking-clone-backend
-- Matches your JPA entities exactly.
-- Postgres: uses IDENTITY + enum types + jsonb.
-- ===========================================

-- Needed for exclusion constraint on availability (no-overlap)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------- ENUM TYPES ----------
DO $$ BEGIN
    CREATE TYPE role_enum AS ENUM ('GUEST', 'PARTNER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE property_type_enum AS ENUM ('APARTMENT', 'HOTEL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE property_status_enum AS ENUM ('DRAFT', 'PUBLISHED', 'PAUSED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE currency_code_enum AS ENUM ('EUR', 'USD', 'GBP');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE parking_policy_enum AS ENUM ('NONE', 'FREE', 'PAID');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE pets_policy_enum AS ENUM ('NO', 'YES', 'UPON_REQUEST');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE amenity_group_enum AS ENUM (
        'GENERAL',
        'COOKING_AND_CLEANING',
        'ENTERTAINMENT',
        'OUTSIDE_AND_VIEW'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------- USERS ----------
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          role_enum NOT NULL DEFAULT 'GUEST',
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ---------- REFRESH TOKENS ----------
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token       VARCHAR(200) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_refresh_token_token ON refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id ON refresh_tokens(user_id);

-- ---------- PROPERTIES ----------
CREATE TABLE IF NOT EXISTS properties (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id           BIGINT NOT NULL,

    type               property_type_enum NOT NULL DEFAULT 'APARTMENT',
    status             property_status_enum NOT NULL DEFAULT 'DRAFT',

    name               VARCHAR(200) NOT NULL,

    price_per_night    NUMERIC(10,2),
    currency           currency_code_enum DEFAULT 'EUR',

    max_guests         INTEGER,
    bathrooms          INTEGER,
    size_sqm           NUMERIC(10,2),

    children_allowed   BOOLEAN NOT NULL DEFAULT TRUE,
    cots_offered       BOOLEAN NOT NULL DEFAULT FALSE,

    breakfast_served   BOOLEAN NOT NULL DEFAULT FALSE,
    parking_policy     parking_policy_enum NOT NULL DEFAULT 'NONE',

    smoking_allowed    BOOLEAN NOT NULL DEFAULT FALSE,
    parties_allowed    BOOLEAN NOT NULL DEFAULT FALSE,
    pets_policy        pets_policy_enum NOT NULL DEFAULT 'NO',

    check_in_from      TIME,
    check_in_until     TIME,
    check_out_from     TIME,
    check_out_until    TIME,

    sleeping_areas_json JSONB,

    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_properties_owner
        FOREIGN KEY (owner_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_properties_owner  ON properties(owner_id);
CREATE INDEX IF NOT EXISTS idx_properties_status ON properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_type   ON properties(type);

-- ---------- PROPERTY ADDRESSES (1:1, PK = FK) ----------
CREATE TABLE IF NOT EXISTS property_addresses (
    property_id    BIGINT PRIMARY KEY,
    country        VARCHAR(120) NOT NULL,
    city           VARCHAR(120) NOT NULL,
    postcode       VARCHAR(32),
    street         VARCHAR(200) NOT NULL,
    street_number  VARCHAR(32),
    lat            DOUBLE PRECISION,
    lng            DOUBLE PRECISION,

    CONSTRAINT fk_property_addresses_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_property_addresses_city     ON property_addresses(city);
CREATE INDEX IF NOT EXISTS idx_property_addresses_country  ON property_addresses(country);
CREATE INDEX IF NOT EXISTS idx_property_addresses_postcode ON property_addresses(postcode);

-- ---------- PROPERTY PHOTOS ----------
CREATE TABLE IF NOT EXISTS property_photos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT NOT NULL,
    url          VARCHAR(600) NOT NULL,
    sort_order   INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_property_photos_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_property_photos_property ON property_photos(property_id);
CREATE INDEX IF NOT EXISTS idx_property_photos_sort     ON property_photos(property_id, sort_order);

-- ---------- AMENITIES ----------
CREATE TABLE IF NOT EXISTS amenities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(80) NOT NULL UNIQUE,
    label       VARCHAR(160) NOT NULL,
    group_name  amenity_group_enum NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_amenities_code ON amenities(code);

-- ---------- PROPERTY_AMENITIES (join) ----------
CREATE TABLE IF NOT EXISTS property_amenities (
    property_id BIGINT NOT NULL,
    amenity_id  BIGINT NOT NULL,

    PRIMARY KEY (property_id, amenity_id),

    CONSTRAINT fk_property_amenities_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_property_amenities_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenities(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_property_amenities_property ON property_amenities(property_id);

-- ---------- LANGUAGES ----------
CREATE TABLE IF NOT EXISTS languages (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(16) NOT NULL UNIQUE,
    label  VARCHAR(120) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_languages_code ON languages(code);

-- ---------- PROPERTY_LANGUAGES (join) ----------
CREATE TABLE IF NOT EXISTS property_languages (
    property_id BIGINT NOT NULL,
    language_id BIGINT NOT NULL,

    PRIMARY KEY (property_id, language_id),

    CONSTRAINT fk_property_languages_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_property_languages_language
        FOREIGN KEY (language_id) REFERENCES languages(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_property_languages_property ON property_languages(property_id);
CREATE INDEX IF NOT EXISTS idx_property_languages_language ON property_languages(language_id);

-- ---------- PROPERTY AVAILABILITY ----------
CREATE TABLE IF NOT EXISTS property_availability (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT NOT NULL,
    start_date   DATE NOT NULL,
    end_date     DATE NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_availability_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,

    -- end exclusive convention still needs start < end
    CONSTRAINT chk_availability_dates CHECK (start_date < end_date)
);

CREATE INDEX IF NOT EXISTS idx_availability_property ON property_availability(property_id);
CREATE INDEX IF NOT EXISTS idx_availability_dates    ON property_availability(start_date, end_date);

