
-- ===========================================
-- V1: Clean baseline schema aligned with current entities.
-- ===========================================

-- ---------- ENUM TYPES ----------
DO $$ BEGIN
    CREATE TYPE property_type_enum AS ENUM ('APARTMENT', 'HOTEL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE property_status_enum AS ENUM ('DRAFT', 'PUBLISHED', 'PAUSED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE currency_code_enum AS ENUM ('EUR', 'USD', 'GBP');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE parking_policy_enum AS ENUM ('NONE', 'FREE', 'PAID');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE pets_policy_enum AS ENUM ('NO', 'YES', 'UPON_REQUEST');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE amenity_group_enum AS ENUM (
        'GENERAL',
        'COOKING_AND_CLEANING',
        'ENTERTAINMENT',
        'OUTSIDE_AND_VIEW'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE booking_status_enum AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE payment_status_enum AS ENUM ('REQUIRES_PAYMENT', 'PROCESSING', 'SUCCEEDED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------- RBAC ----------
CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS capabilities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS roles_capabilities (
    role_id       BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, capability_id),
    CONSTRAINT fk_roles_capabilities_role
        FOREIGN KEY (role_id) REFERENCES roles(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_capabilities_capability
        FOREIGN KEY (capability_id) REFERENCES capabilities(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_roles_capabilities_capability
    ON roles_capabilities(capability_id);

-- ---------- COUNTRIES ----------
CREATE TABLE IF NOT EXISTS countries (
    code       VARCHAR(2) PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ
);

INSERT INTO countries (code, name) VALUES
('GR', 'Greece'),
('FR', 'France'),
('DE', 'Germany'),
('IT', 'Italy'),
('ES', 'Spain'),
('GB', 'United Kingdom'),
('US', 'United States'),
('NL', 'Netherlands'),
('BE', 'Belgium'),
('PT', 'Portugal'),
('AT', 'Austria'),
('CH', 'Switzerland'),
('SE', 'Sweden'),
('NO', 'Norway')
ON CONFLICT (code) DO NOTHING;

-- ---------- STATIC LOOKUPS ----------
CREATE TABLE IF NOT EXISTS languages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(16) NOT NULL UNIQUE,
    label      VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_languages_code ON languages(code);

CREATE TABLE IF NOT EXISTS amenities (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(80) NOT NULL UNIQUE,
    label      VARCHAR(160) NOT NULL,
    group_name amenity_group_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_amenities_code ON amenities(code);

-- ---------- PERSONAL INFO ----------
CREATE TABLE IF NOT EXISTS personal_info (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code VARCHAR(2) NOT NULL,
    first_name   VARCHAR(120) NOT NULL,
    last_name    VARCHAR(120) NOT NULL,
    CONSTRAINT fk_personal_info_country
        FOREIGN KEY (country_code) REFERENCES countries(code)
);

-- ---------- USERS ----------
CREATE TABLE IF NOT EXISTS users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             UUID NOT NULL,
    email            VARCHAR(320) NOT NULL UNIQUE,
    password_hash    TEXT NOT NULL,
    role_id          BIGINT NOT NULL,
    personal_info_id BIGINT,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_users_personal_info
        FOREIGN KEY (personal_info_id) REFERENCES personal_info(id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_uuid ON users(uuid);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_personal_info_id
    ON users(personal_info_id)
    WHERE personal_info_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users(role_id);

-- ---------- REFRESH TOKENS ----------
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID NOT NULL,
    user_id    BIGINT NOT NULL,
    token      VARCHAR(200) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_refresh_tokens_uuid ON refresh_tokens(uuid);
CREATE UNIQUE INDEX IF NOT EXISTS idx_refresh_token_token ON refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id ON refresh_tokens(user_id);
-- ---------- ADDRESSES ----------
CREATE TABLE IF NOT EXISTS addresses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID NOT NULL,
    country_code  VARCHAR(2) NOT NULL,
    city          VARCHAR(120) NOT NULL,
    postcode      VARCHAR(32),
    street        VARCHAR(200) NOT NULL,
    street_number VARCHAR(32),
    floor_number  VARCHAR(10),
    lat           DOUBLE PRECISION,
    lng           DOUBLE PRECISION,
    CONSTRAINT fk_addresses_country
        FOREIGN KEY (country_code) REFERENCES countries(code)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_addresses_uuid ON addresses(uuid);
CREATE INDEX IF NOT EXISTS idx_addresses_city ON addresses(city);
CREATE INDEX IF NOT EXISTS idx_addresses_country ON addresses(country_code);
CREATE INDEX IF NOT EXISTS idx_addresses_postcode ON addresses(postcode);

-- ---------- PROPERTIES ----------
CREATE TABLE IF NOT EXISTS properties (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID NOT NULL,
    owner_id            BIGINT NOT NULL,
    address_id          BIGINT,
    type                property_type_enum NOT NULL DEFAULT 'APARTMENT',
    status              property_status_enum NOT NULL DEFAULT 'DRAFT',
    name                VARCHAR(200) NOT NULL,
    price_per_night     NUMERIC(10,2),
    currency            currency_code_enum NOT NULL DEFAULT 'EUR',
    max_guests          INTEGER,
    bathrooms           INTEGER,
    size_sqm            NUMERIC(10,2),
    children_allowed    BOOLEAN NOT NULL DEFAULT TRUE,
    cots_offered        BOOLEAN NOT NULL DEFAULT FALSE,
    breakfast_served    BOOLEAN NOT NULL DEFAULT FALSE,
    parking_policy      parking_policy_enum NOT NULL DEFAULT 'NONE',
    smoking_allowed     BOOLEAN NOT NULL DEFAULT FALSE,
    parties_allowed     BOOLEAN NOT NULL DEFAULT FALSE,
    pets_policy         pets_policy_enum NOT NULL DEFAULT 'NO',
    check_in_from       TIME,
    check_in_until      TIME,
    check_out_from      TIME,
    check_out_until     TIME,
    sleeping_areas_json JSONB,
    living_room_count   INTEGER NOT NULL,
    bedroom_count       INTEGER NOT NULL,
    bed_count           INTEGER NOT NULL,
    bed_summary         VARCHAR(255) NOT NULL,
    main_photo_id       BIGINT,
    main_photo_url      VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_properties_owner
        FOREIGN KEY (owner_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_properties_address
        FOREIGN KEY (address_id) REFERENCES addresses(id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_properties_uuid ON properties(uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uq_properties_address_id
    ON properties(address_id)
    WHERE address_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_properties_owner ON properties(owner_id);
CREATE INDEX IF NOT EXISTS idx_properties_status ON properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_type ON properties(type);

-- ---------- PROPERTY ATTACHMENTS ----------
CREATE TABLE IF NOT EXISTS property_attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID NOT NULL,
    property_id BIGINT NOT NULL,
    url         VARCHAR(600) NOT NULL,
    public_id   VARCHAR(600) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT fk_property_attachments_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_property_attachments_uuid ON property_attachments(uuid);
CREATE INDEX IF NOT EXISTS idx_property_attachments_property_id ON property_attachments(property_id);
CREATE INDEX IF NOT EXISTS idx_property_attachments_url ON property_attachments(url);

-- ---------- PROPERTY AMENITIES ----------
CREATE TABLE IF NOT EXISTS properties_amenities (
    property_id BIGINT NOT NULL,
    amenity_id  BIGINT NOT NULL,
    PRIMARY KEY (property_id, amenity_id),
    CONSTRAINT fk_properties_amenities_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_properties_amenities_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenities(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_properties_amenities_property
    ON properties_amenities(property_id);
CREATE INDEX IF NOT EXISTS idx_properties_amenities_amenity
    ON properties_amenities(amenity_id);

-- ---------- PROPERTY LANGUAGES ----------
CREATE TABLE IF NOT EXISTS properties_languages (
    property_id BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    PRIMARY KEY (property_id, language_id),
    CONSTRAINT fk_properties_languages_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_properties_languages_language
        FOREIGN KEY (language_id) REFERENCES languages(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_properties_languages_property
    ON properties_languages(property_id);
CREATE INDEX IF NOT EXISTS idx_properties_languages_language
    ON properties_languages(language_id);
-- ---------- BOOKINGS ----------
CREATE TABLE IF NOT EXISTS bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              UUID NOT NULL,
    property_id       BIGINT NOT NULL,
    guest_id          BIGINT NOT NULL,
    check_in_date     DATE NOT NULL,
    check_out_date    DATE NOT NULL,
    guest_count       INTEGER NOT NULL DEFAULT 1,
    status            booking_status_enum NOT NULL DEFAULT 'CONFIRMED',
    payment_intent_id VARCHAR(120),
    payment_status    payment_status_enum NOT NULL DEFAULT 'REQUIRES_PAYMENT',
    amount_total      NUMERIC(10,2),
    paid_at           TIMESTAMPTZ,
    hold_expires_at   TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_bookings_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_bookings_guest
        FOREIGN KEY (guest_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_booking_dates CHECK (check_in_date < check_out_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bookings_uuid ON bookings(uuid);
CREATE INDEX IF NOT EXISTS idx_bookings_property_checkin ON bookings(property_id, check_in_date);
CREATE INDEX IF NOT EXISTS idx_bookings_property_checkout ON bookings(property_id, check_out_date);
CREATE INDEX IF NOT EXISTS idx_bookings_guest ON bookings(guest_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_status_hold_expires ON bookings(status, hold_expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_bookings_payment_intent
    ON bookings(payment_intent_id)
    WHERE payment_intent_id IS NOT NULL;

-- ---------- BOOKING CHECKOUT DETAILS ----------
CREATE TABLE IF NOT EXISTS booking_checkout_details (
    booking_id         BIGINT PRIMARY KEY,
    uuid               UUID NOT NULL,
    traveling_for_work BOOLEAN NOT NULL DEFAULT FALSE,
    title              VARCHAR(20),
    first_name         VARCHAR(120) NOT NULL,
    last_name          VARCHAR(120) NOT NULL,
    contact_email      VARCHAR(320) NOT NULL,
    phone_country_code VARCHAR(10),
    phone_number       VARCHAR(40),
    special_request    VARCHAR(1000),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted            BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT fk_booking_checkout_details_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_checkout_details_uuid ON booking_checkout_details(uuid);
CREATE INDEX IF NOT EXISTS idx_booking_checkout_details_email
    ON booking_checkout_details(contact_email);

-- ---------- PROPERTY AVAILABILITY ----------
CREATE TABLE IF NOT EXISTS property_availability (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID NOT NULL,
    property_id BIGINT NOT NULL,
    booking_id  BIGINT UNIQUE,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT fk_availability_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_availability_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_availability_dates CHECK (start_date < end_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_property_availability_uuid ON property_availability(uuid);
CREATE INDEX IF NOT EXISTS idx_availability_property ON property_availability(property_id);
CREATE INDEX IF NOT EXISTS idx_availability_dates ON property_availability(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_availability_booking ON property_availability(booking_id);

-- ---------- REVIEWS ----------
CREATE TABLE IF NOT EXISTS reviews (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID NOT NULL,
    booking_id         BIGINT NOT NULL,
    property_id        BIGINT NOT NULL,
    guest_id           BIGINT NOT NULL,
    rating             INTEGER NOT NULL,
    positive_comment   VARCHAR(1500),
    negative_comment   VARCHAR(1500),
    owner_response     VARCHAR(1500),
    owner_responded_at TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted            BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT uk_reviews_booking UNIQUE (booking_id),
    CONSTRAINT fk_reviews_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reviews_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reviews_guest
        FOREIGN KEY (guest_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 10),
    CONSTRAINT chk_reviews_positive_or_negative CHECK (
        (positive_comment IS NOT NULL AND length(btrim(positive_comment)) > 0)
        OR
        (negative_comment IS NOT NULL AND length(btrim(negative_comment)) > 0)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_reviews_uuid ON reviews(uuid);
CREATE INDEX IF NOT EXISTS idx_reviews_property_created ON reviews(property_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reviews_guest_created ON reviews(guest_id, created_at);
-- ---------- CHATS ----------
CREATE TABLE IF NOT EXISTS chats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            UUID NOT NULL,
    booking_id      BIGINT NOT NULL UNIQUE,
    last_message_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT fk_chats_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_chats_uuid ON chats(uuid);

-- ---------- CHAT PARTICIPANTS ----------
CREATE TABLE IF NOT EXISTS chat_participants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id      BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    last_read_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT fk_chat_participants_chat
        FOREIGN KEY (chat_id) REFERENCES chats(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_chat_participants_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_chat_participant UNIQUE (chat_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_chat_participants_chat ON chat_participants(chat_id);
CREATE INDEX IF NOT EXISTS idx_chat_participants_user ON chat_participants(user_id);

-- ---------- MESSAGES ----------
CREATE TABLE IF NOT EXISTS messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID NOT NULL,
    chat_id    BIGINT NOT NULL,
    author_id  BIGINT NOT NULL,
    content    VARCHAR(4000),
    photo      VARCHAR(600),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_messages_chat
        FOREIGN KEY (chat_id) REFERENCES chats(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_messages_author
        FOREIGN KEY (author_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_messages_content_or_photo CHECK (
        (content IS NOT NULL AND length(btrim(content)) > 0)
        OR
        (photo IS NOT NULL AND length(btrim(photo)) > 0)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_uuid ON messages(uuid);
CREATE INDEX IF NOT EXISTS idx_messages_chat_created ON messages(chat_id, created_at);
