-- ===========================================
-- V5: Bookings (reservations)
-- ===========================================

-- Booking status enum (Postgres)
DO $$ BEGIN
    CREATE TYPE booking_status_enum AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS bookings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    property_id     BIGINT NOT NULL,
    guest_id        BIGINT NOT NULL,

    check_in_date   DATE NOT NULL,
    check_out_date  DATE NOT NULL,

    guest_count     INTEGER NOT NULL DEFAULT 1,

    status          booking_status_enum NOT NULL DEFAULT 'CONFIRMED',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_bookings_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bookings_guest
        FOREIGN KEY (guest_id) REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_booking_dates CHECK (check_in_date < check_out_date)
);

-- Useful indexes for dashboard queries
CREATE INDEX IF NOT EXISTS idx_bookings_property_checkin
    ON bookings(property_id, check_in_date);

CREATE INDEX IF NOT EXISTS idx_bookings_property_checkout
    ON bookings(property_id, check_out_date);

CREATE INDEX IF NOT EXISTS idx_bookings_guest
    ON bookings(guest_id);

CREATE INDEX IF NOT EXISTS idx_bookings_status
    ON bookings(status);
