-- ===========================================
-- V7: Reviews
-- - One review per booking
-- - Requires at least one of positive/negative comment
-- - Supports partner/owner response
-- ===========================================

CREATE TABLE IF NOT EXISTS reviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id          BIGINT NOT NULL,
    property_id         BIGINT NOT NULL,
    guest_id            BIGINT NOT NULL,

    rating              INTEGER NOT NULL,

    positive_comment    VARCHAR(1500),
    negative_comment    VARCHAR(1500),

    owner_response      VARCHAR(1500),
    owner_responded_at  TIMESTAMPTZ,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- One review per booking
    CONSTRAINT uk_reviews_booking UNIQUE (booking_id),

    CONSTRAINT fk_reviews_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reviews_property
        FOREIGN KEY (property_id) REFERENCES properties(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reviews_guest
        FOREIGN KEY (guest_id) REFERENCES users(id)
        ON DELETE CASCADE,

    -- Rating range (adjust to 1..5 if you prefer)
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 10),

    -- At least one comment must be provided (non-blank)
    CONSTRAINT chk_reviews_positive_or_negative CHECK (
        (positive_comment IS NOT NULL AND length(btrim(positive_comment)) > 0)
        OR
        (negative_comment IS NOT NULL AND length(btrim(negative_comment)) > 0)
    )
);

-- Indexes for property page sorting/filtering
CREATE INDEX IF NOT EXISTS idx_reviews_property_created
    ON reviews(property_id, created_at);

-- Indexes for "my reviews" / guest history
CREATE INDEX IF NOT EXISTS idx_reviews_guest_created
    ON reviews(guest_id, created_at);

-- Useful for joins / lookups by booking
CREATE INDEX IF NOT EXISTS idx_reviews_booking
    ON reviews(booking_id);
