-- Move personal data from users into personal_info table.
-- Backfills existing rows and preserves current data.

CREATE TABLE IF NOT EXISTS personal_info (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code VARCHAR(2) NOT NULL,
    first_name   VARCHAR(120) NOT NULL,
    last_name    VARCHAR(120) NOT NULL,
    CONSTRAINT fk_personal_info_country
        FOREIGN KEY (country_code) REFERENCES countries(code)
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS personal_info_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'users'
          AND column_name = 'country_code'
    ) THEN
        ALTER TABLE personal_info
            ADD COLUMN IF NOT EXISTS legacy_user_id BIGINT UNIQUE;

        INSERT INTO personal_info (country_code, first_name, last_name, legacy_user_id)
        SELECT u.country_code, u.first_name, u.last_name, u.id
        FROM users u
        WHERE u.personal_info_id IS NULL
          AND NOT EXISTS (
              SELECT 1
              FROM personal_info pi
              WHERE pi.legacy_user_id = u.id
          );

        UPDATE users u
        SET personal_info_id = pi.id
        FROM personal_info pi
        WHERE u.personal_info_id IS NULL
          AND pi.legacy_user_id = u.id;

        ALTER TABLE personal_info
            DROP COLUMN IF EXISTS legacy_user_id;
    END IF;
END $$;

DO $$ BEGIN
    ALTER TABLE users
        ADD CONSTRAINT fk_users_personal_info
            FOREIGN KEY (personal_info_id) REFERENCES personal_info(id)
            ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_personal_info_id
    ON users(personal_info_id)
    WHERE personal_info_id IS NOT NULL;

DROP INDEX IF EXISTS idx_users_country_code;
DROP INDEX IF EXISTS idx_users_last_name;

DO $$ BEGIN
    ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_country;
EXCEPTION WHEN undefined_object THEN NULL; END $$;

ALTER TABLE users DROP COLUMN IF EXISTS country_code;
ALTER TABLE users DROP COLUMN IF EXISTS first_name;
ALTER TABLE users DROP COLUMN IF EXISTS last_name;
